"""init full schema

Revision ID: 064d768677b9
Revises: 
Create Date: 2025-06-25 15:51:13.818867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064d768677b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wechat_nickname', sa.String(length=128), nullable=False),
    sa.Column('real_name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('name_abbreviation', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wechat_nickname')
    )
    op.create_table('keyword_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('project_type', sa.String(length=32), nullable=True),
    sa.Column('external_group_name', sa.Text(), nullable=True),
    sa.Column('internal_group_name', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('efficiency_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('active_employees', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('health_details', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('efficiency_metrics', sa.Text(), nullable=True),
    sa.Column('quality_metrics', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=256), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_md5', sa.String(length=32), nullable=True),
    sa.Column('file_extension', sa.String(length=16), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=True),
    sa.Column('file_category', sa.String(length=64), nullable=True),
    sa.Column('task_identifier', sa.String(length=256), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('workload_amount', sa.String(length=32), nullable=True),
    sa.Column('author_abbreviation', sa.String(length=16), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('workload_equivalent', sa.Float(), nullable=True),
    sa.Column('is_final_version', sa.Boolean(), nullable=True),
    sa.Column('time_to_final', sa.Float(), nullable=True),
    sa.Column('task_group_id', sa.String(length=64), nullable=True),
    sa.Column('parent_asset_id', sa.Integer(), nullable=True),
    sa.Column('chatroom_name', sa.String(length=128), nullable=True),
    sa.Column('message_seq', sa.String(length=64), nullable=True),
    sa.Column('uploader', sa.String(length=128), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archive_path', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['employee_mappings.id'], ),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=True),
    sa.Column('talker_name', sa.String(length=128), nullable=False),
    sa.Column('sender_name', sa.String(length=128), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('message_subtype', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('file_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=256), nullable=False),
    sa.Column('standardized_name', sa.String(length=256), nullable=False),
    sa.Column('project_name', sa.String(length=128), nullable=False),
    sa.Column('work_order', sa.String(length=128), nullable=True),
    sa.Column('workload', sa.String(length=32), nullable=True),
    sa.Column('author_abbreviation', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('file_extension', sa.String(length=16), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.Column('uploader', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_md5', sa.String(length=32), nullable=True),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('file_type', sa.String(length=32), nullable=True),
    sa.Column('file_category', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archive_path', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('chatroom_name', sa.String(length=128), nullable=True),
    sa.Column('message_seq', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_mappings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('chatroom_name', sa.String(length=128), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('analyzed_messages', sa.Integer(), nullable=True),
    sa.Column('positive_score', sa.Float(), nullable=True),
    sa.Column('negative_score', sa.Float(), nullable=True),
    sa.Column('neutral_score', sa.Float(), nullable=True),
    sa.Column('overall_sentiment', sa.String(length=16), nullable=True),
    sa.Column('keyword_stats', sa.Text(), nullable=True),
    sa.Column('top_keywords', sa.Text(), nullable=True),
    sa.Column('sentiment_trend', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_mappings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('synonyms', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['keyword_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_chatrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('chatroom_id', sa.String(length=128), nullable=False),
    sa.Column('chatroom_name', sa.String(length=128), nullable=False),
    sa.Column('chatroom_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_sync_time', sa.DateTime(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('efficiency_score', sa.Float(), nullable=True),
    sa.Column('iteration_count', sa.Integer(), nullable=True),
    sa.Column('rework_factor', sa.Float(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('first_submission_time', sa.DateTime(), nullable=True),
    sa.Column('final_submission_time', sa.DateTime(), nullable=True),
    sa.Column('total_work_time', sa.Float(), nullable=True),
    sa.Column('analysis_details', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('improvement_suggestions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('file_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_record_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_md5', sa.String(length=32), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.Column('uploader', sa.String(length=128), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_record_id'], ['file_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_seq', sa.String(length=64), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('keyword_text', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_keywords')
    op.drop_table('file_versions')
    op.drop_table('asset_analyses')
    op.drop_table('project_chatrooms')
    op.drop_table('keywords')
    op.drop_table('keyword_analyses')
    op.drop_table('file_records')
    op.drop_table('chat_messages')
    op.drop_table('assets')
    op.drop_table('projects')
    op.drop_table('keyword_categories')
    op.drop_table('employee_mappings')
    # ### end Alembic commands ###
