"""add ondelete cascade to project_id foreign keys

Revision ID: 2ddf19fcd429
Revises: add_deduplication_constraints
Create Date: 2025-06-27 16:59:46.109170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ddf19fcd429'
down_revision: Union[str, Sequence[str], None] = 'add_deduplication_constraints'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_health_stats')
    op.drop_table('employee_load_baselines')
    op.drop_table('workload_weights')
    op.drop_table('unmatched_persons')
    op.drop_table('workload_records')
    op.drop_table('project_difficulty_indices')
    op.drop_constraint(op.f('assets_project_id_fkey'), 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chat_messages', 'message_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_constraint(op.f('chat_messages_project_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('file_records_project_id_fkey'), 'file_records', type_='foreignkey')
    op.create_foreign_key(None, 'file_records', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('keyword_analyses_project_id_fkey'), 'keyword_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'keyword_analyses', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('risk_events_project_id_fkey'), 'risk_events', type_='foreignkey')
    op.create_foreign_key(None, 'risk_events', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risk_events', type_='foreignkey')
    op.create_foreign_key(op.f('risk_events_project_id_fkey'), 'risk_events', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'keyword_analyses', type_='foreignkey')
    op.create_foreign_key(op.f('keyword_analyses_project_id_fkey'), 'keyword_analyses', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'file_records', type_='foreignkey')
    op.create_foreign_key(op.f('file_records_project_id_fkey'), 'file_records', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_project_id_fkey'), 'chat_messages', 'projects', ['project_id'], ['id'])
    op.alter_column('chat_messages', 'message_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key(op.f('assets_project_id_fkey'), 'assets', 'projects', ['project_id'], ['id'])
    op.create_table('project_difficulty_indices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('complexity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('client_difficulty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('requirement_clarity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timeline_pressure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('resource_adequacy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_employee_revisions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('team_baseline_revisions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('difficulty_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('outlier_employees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('similar_projects_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('industry_benchmark', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('calculation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_difficulty_indices_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_difficulty_indices_pkey'))
    )
    op.create_table('workload_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('output_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('output_value', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('we_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_final', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_iteration', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('iteration_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_message_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('business_unit', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_mappings.id'], name=op.f('workload_records_employee_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('workload_records_project_id_fkey')),
    sa.ForeignKeyConstraint(['related_file_id'], ['file_records.id'], name=op.f('workload_records_related_file_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workload_records_pkey'))
    )
    op.create_table('unmatched_persons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('remark', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('unmatched_persons_pkey'))
    )
    op.create_table('workload_weights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('output_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('business_unit', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('we_per_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_final', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('iteration_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('workload_weights_pkey'))
    )
    op.create_table('employee_load_baselines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('avg_revisions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_we_per_day', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_final_we', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_process_we', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_projects', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_outputs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calculation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_mappings.id'], name=op.f('employee_load_baselines_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_load_baselines_pkey'))
    )
    op.create_table('project_health_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('health_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_time_to_final', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_revisions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('risk_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('warning_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('negative_sentiment_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_health_stats_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_health_stats_pkey'))
    )
    # ### end Alembic commands ###
