"""add_asset_models

Revision ID: c42a0d8219af
Revises: abcd1234efgh
Create Date: 2025-06-23 13:00:22.682322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c42a0d8219af'
down_revision: Union[str, Sequence[str], None] = 'abcd1234efgh'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_difficulty_indices')
    op.drop_table('employee_load_baselines')
    op.drop_table('workload_records')
    op.drop_table('risk_events')
    op.drop_table('asset_analyses')
    op.drop_table('workload_weights')
    op.drop_table('unmatched_persons')
    op.drop_table('assets')
    op.drop_table('project_health_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_health_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('health_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_time_to_final', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_revisions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('risk_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('warning_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('negative_sentiment_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_health_stats_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_health_stats_pkey'))
    )
    op.create_table('assets',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('assets_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('file_md5', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('file_extension', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('file_category', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('task_identifier', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('submission_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workload_amount', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('author_abbreviation', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('workload_equivalent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_final_version', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('time_to_final', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('task_group_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('parent_asset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chatroom_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('message_seq', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('uploader', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('archive_path', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['employee_mappings.id'], name='assets_author_id_fkey'),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['assets.id'], name='assets_parent_asset_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='assets_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assets_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('unmatched_persons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('remark', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('unmatched_persons_pkey'))
    )
    op.create_table('workload_weights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('output_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('business_unit', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('we_per_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_final', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('iteration_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('workload_weights_pkey'))
    )
    op.create_table('asset_analyses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('efficiency_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('iteration_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rework_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('complexity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('first_submission_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('final_submission_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_work_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('analysis_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('risk_factors', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('improvement_suggestions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('asset_analyses_asset_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_analyses_pkey')),
    sa.UniqueConstraint('asset_id', name=op.f('asset_analyses_asset_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('risk_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('event_desc', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('event_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=8), server_default=sa.text("'中'::character varying"), autoincrement=False, nullable=True),
    sa.Column('resolved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('attribution', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_mappings.id'], name=op.f('risk_events_employee_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('risk_events_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('risk_events_pkey'))
    )
    op.create_table('workload_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('output_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('output_value', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('we_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_final', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_iteration', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('iteration_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_message_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('business_unit', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_mappings.id'], name=op.f('workload_records_employee_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('workload_records_project_id_fkey')),
    sa.ForeignKeyConstraint(['related_file_id'], ['file_records.id'], name=op.f('workload_records_related_file_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workload_records_pkey'))
    )
    op.create_table('employee_load_baselines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('avg_revisions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_we_per_day', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_final_we', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_process_we', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_projects', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_outputs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('calculation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_mappings.id'], name=op.f('employee_load_baselines_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_load_baselines_pkey'))
    )
    op.create_table('project_difficulty_indices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('complexity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('client_difficulty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('requirement_clarity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timeline_pressure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('resource_adequacy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_employee_revisions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('team_baseline_revisions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('difficulty_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('outlier_employees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('similar_projects_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('industry_benchmark', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('calculation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_difficulty_indices_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_difficulty_indices_pkey'))
    )
    # ### end Alembic commands ###
