"""create_assets_table

Revision ID: d2a7fbf6ef66
Revises: 6dd762a0ff7c
Create Date: 2025-06-23 13:17:43.617854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a7fbf6ef66'
down_revision: Union[str, Sequence[str], None] = '6dd762a0ff7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=256), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_md5', sa.String(length=32), nullable=True),
    sa.Column('file_extension', sa.String(length=16), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=True),
    sa.Column('file_category', sa.String(length=64), nullable=True),
    sa.Column('task_identifier', sa.String(length=256), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('workload_amount', sa.String(length=32), nullable=True),
    sa.Column('author_abbreviation', sa.String(length=16), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('workload_equivalent', sa.Float(), nullable=True),
    sa.Column('is_final_version', sa.Boolean(), nullable=True),
    sa.Column('time_to_final', sa.Float(), nullable=True),
    sa.Column('task_group_id', sa.String(length=64), nullable=True),
    sa.Column('parent_asset_id', sa.Integer(), nullable=True),
    sa.Column('chatroom_name', sa.String(length=128), nullable=True),
    sa.Column('message_seq', sa.String(length=64), nullable=True),
    sa.Column('uploader', sa.String(length=128), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archive_path', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['employee_mappings.id'], ),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('efficiency_score', sa.Float(), nullable=True),
    sa.Column('iteration_count', sa.Integer(), nullable=True),
    sa.Column('rework_factor', sa.Float(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('first_submission_time', sa.DateTime(), nullable=True),
    sa.Column('final_submission_time', sa.DateTime(), nullable=True),
    sa.Column('total_work_time', sa.Float(), nullable=True),
    sa.Column('analysis_details', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('improvement_suggestions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_analyses')
    op.drop_table('assets')
    # ### end Alembic commands ###
