"""add duration_hours to file_records

Revision ID: e0ec0404bf4e
Revises: 836cfbb6e10b
Create Date: 2025-06-19 14:57:32.204118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ec0404bf4e'
down_revision: Union[str, Sequence[str], None] = '836cfbb6e10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('duration_hours', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'duration_hours')
    # ### end Alembic commands ###
